{% set name = "retworkx" %}
{% set version = "0.11.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/retworkx-{{ version }}.tar.gz
    sha256: a4c2a5ad3f8402493d41ad20ad91a03777ea214a3636c290272bbfaf36161161

build:
  number: 2
  script:
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
    - make
  host:
    - pip
    - python
    - setuptools
    - setuptools-rust
    - wheel
  run:
    - numpy >=1.16.0
    - python
  run_constrained:
    - matplotlib >=3.0
    - pillow >=5.4

test:
  imports:
    - retworkx
    - retworkx.visualization
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Qiskit/retworkx
  summary: A python graph library implemented in Rust
  license: Apache-2.0
  license_file:
    - LICENSE
    # Included in https://github.com/Qiskit/retworkx/pull/500
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - BastianZim
